#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/glm46v/modular_glm46v.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_glm46v.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 the HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


from transformers.configuration_utils import PretrainedConfig as PreTrainedConfig
from transformers import AutoConfig, AutoModel

# Flag to track if we've registered
_REGISTERED = False


def _register_glm4v_configs():
    """Register GLM4V configs with Auto classes if not already registered."""
    global _REGISTERED
    if _REGISTERED:
        return

    try:
        # Register vision config
        AutoConfig.register("glm4v_vision", Glm4vVisionConfig)
        # Register text config
        AutoConfig.register("glm4v_text", Glm4vTextConfig)
        # Register main config
        AutoConfig.register("glm46v", Glm46VConfig)
        _REGISTERED = True
    except Exception:
        # Already registered or other issue
        pass


class Glm4vVisionConfig(PreTrainedConfig):
    """Configuration for GLM-4V vision encoder."""
    model_type = "glm4v_vision"

    def __init__(
        self,
        hidden_size=1536,
        intermediate_size=13696,
        num_heads=12,
        depth=24,
        patch_size=14,
        image_size=336,
        in_channels=3,
        hidden_act="silu",
        attention_dropout=0.0,
        hidden_dropout_prob=0.0,
        initializer_range=0.02,
        rms_norm_eps=1e-5,
        out_hidden_size=4096,
        spatial_merge_size=2,
        temporal_patch_size=2,
        attention_bias=False,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_heads = num_heads
        self.depth = depth
        self.patch_size = patch_size
        self.image_size = image_size
        self.in_channels = in_channels
        self.hidden_act = hidden_act
        self.attention_dropout = attention_dropout
        self.hidden_dropout_prob = hidden_dropout_prob
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.out_hidden_size = out_hidden_size
        self.spatial_merge_size = spatial_merge_size
        self.temporal_patch_size = temporal_patch_size
        self.attention_bias = attention_bias


class Glm4vTextConfig(PreTrainedConfig):
    """Configuration for GLM-4V text decoder."""
    model_type = "glm4v_text"

    def __init__(
        self,
        vocab_size=151552,
        hidden_size=4096,
        intermediate_size=13696,
        num_hidden_layers=40,
        num_attention_heads=32,
        num_key_value_heads=2,
        hidden_act="silu",
        max_position_embeddings=131072,
        initializer_range=0.02,
        rms_norm_eps=1e-5,
        use_cache=True,
        pad_token_id=151329,
        eos_token_id=None,
        attention_bias=True,
        attention_dropout=0.0,
        rope_theta=500000,
        **kwargs,
    ):
        super().__init__(**kwargs)
        self.vocab_size = vocab_size
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.hidden_act = hidden_act
        self.max_position_embeddings = max_position_embeddings
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.pad_token_id = pad_token_id
        self.eos_token_id = eos_token_id
        self.attention_bias = attention_bias
        self.attention_dropout = attention_dropout
        self.rope_theta = rope_theta


class Glm46VConfig(PreTrainedConfig):
    """Configuration for GLM-4.6V model."""

    model_type = "glm46v"
    keys_to_ignore_at_inference = ["past_key_values"]

    def __init__(
        self,
        text_config=None,
        vision_config=None,
        image_token_id=151343,
        video_token_id=151344,
        image_start_token_id=151339,
        image_end_token_id=151340,
        video_start_token_id=151361,
        video_end_token_id=151362,
        **kwargs,
    ):
        # Handle vision config
        if isinstance(vision_config, dict):
            self.vision_config = Glm4vVisionConfig(**vision_config)
        elif vision_config is None:
            self.vision_config = Glm4vVisionConfig()
        else:
            self.vision_config = vision_config

        # Handle text config
        if isinstance(text_config, dict):
            self.text_config = Glm4vTextConfig(**text_config)
        elif text_config is None:
            self.text_config = Glm4vTextConfig()
        else:
            self.text_config = text_config

        self.image_token_id = image_token_id
        self.video_token_id = video_token_id
        self.video_start_token_id = video_start_token_id
        self.video_end_token_id = video_end_token_id
        self.image_start_token_id = image_start_token_id
        self.image_end_token_id = image_end_token_id

        super().__init__(**kwargs)


__all__ = ["Glm46VConfig"]
